// ── lib/solana.ts — Client-side Solana + Metaplex UMI helpers ─
// This file runs in the browser (client components only).
//
// Exports:
//   mintTicketNFT      — Mint a new Metaplex NFT for a ticket
//   listTicketOnChain  — Call Anchor list_ticket instruction
//   fetchWalletNFTs    — Fetch all Ticket Mint NFTs owned by a wallet
//   cancelListingOnChain — Call Anchor cancel_listing instruction

import {
  Connection,
  PublicKey,
  Transaction,
  clusterApiUrl,
} from "@solana/web3.js";
import { createUmi } from "@metaplex-foundation/umi-bundle-defaults";
import { type Umi } from "@metaplex-foundation/umi";
import { walletAdapterIdentity } from "@metaplex-foundation/umi-signer-wallet-adapters";
import { mplTokenMetadata } from "@metaplex-foundation/mpl-token-metadata";
import {
  createNft,
  fetchDigitalAsset,
  fetchAllDigitalAssetByOwner,
  type DigitalAsset,
} from "@metaplex-foundation/mpl-token-metadata";
import {
  generateSigner,
  percentAmount,
  publicKey as umiPublicKey,
  createSignerFromKeypair,
  signerIdentity,
} from "@metaplex-foundation/umi";
import { base58 } from "@metaplex-foundation/umi/serializers";
import * as anchor from "@coral-xyz/anchor";
import { Program, AnchorProvider, web3, BN } from "@coral-xyz/anchor";

// Program IDL — generated by `anchor build`
// In production, import the generated IDL from target/idl/
import IDL from "./idl/ticket_mint_marketplace.json";

// Deferred — avoids calling new PublicKey() with placeholder strings at
// module load time (which would throw during Next.js build page collection).
function getProgramId(): PublicKey {
  return new PublicKey(
    process.env.NEXT_PUBLIC_PROGRAM_ID ?? PublicKey.default.toBase58()
  );
}

function getPlatformFeeWallet(): PublicKey {
  return new PublicKey(
    process.env.NEXT_PUBLIC_PLATFORM_FEE_WALLET ?? PublicKey.default.toBase58()
  );
}

const RPC_ENDPOINT =
  process.env.NEXT_PUBLIC_RPC_ENDPOINT ?? clusterApiUrl("devnet");

// ── Connection singleton ──────────────────────────────────────
export function getConnection(): Connection {
  return new Connection(RPC_ENDPOINT, "confirmed");
}

// ── UMI instance factory ──────────────────────────────────────
// Creates a UMI instance wired to the current wallet adapter signer.
// Call this inside components that have access to the wallet adapter.
export function createUmiWithWallet(wallet: any): Umi {
  const umi = createUmi(RPC_ENDPOINT)
    .use(mplTokenMetadata())
    .use(walletAdapterIdentity(wallet));
  return umi;
}

// ── NFT Metadata attribute type ───────────────────────────────
export interface NFTAttribute {
  trait_type: string;
  value: string;
}

export interface MintTicketParams {
  walletPublicKey: string;
  signTransaction: any;
  metadata: {
    name: string;
    symbol: string;
    description: string;
    attributes: NFTAttribute[];
  };
}

// ── mintTicketNFT ─────────────────────────────────────────────
// Mints a new Metaplex Token Metadata NFT representing one ticket.
//
// Metaplex UMI flow:
//   1. Generate a new mint keypair (the NFT mint address)
//   2. Upload metadata JSON to a public URI (we use a data URI for
//      the MVP; replace with Arweave/IPFS in production)
//   3. Call createNft() — this creates:
//        - The SPL Mint account (supply = 1, decimals = 0)
//        - The Metaplex Metadata PDA
//        - The Metaplex MasterEdition PDA (makes it a true 1/1 NFT)
//        - The seller's Associated Token Account
//   4. Returns the mint address string

export async function mintTicketNFT(params: MintTicketParams): Promise<string> {
  const { walletPublicKey, signTransaction, metadata } = params;

  const connection = getConnection();

  // Build a wallet-adapter-compatible signer
  const walletAdapter = {
    publicKey: new PublicKey(walletPublicKey),
    signTransaction,
    signAllTransactions: async (txs: Transaction[]) =>
      Promise.all(txs.map(signTransaction)),
  };

  // Create UMI instance with the wallet adapter identity
  const umi = createUmi(RPC_ENDPOINT)
    .use(mplTokenMetadata())
    .use(walletAdapterIdentity(walletAdapter as any));

  // Generate a fresh mint keypair for this NFT
  const mintKeypair = generateSigner(umi);

  // Build metadata URI
  // MVP: encode as a data URI.  Production: upload to Arweave via Irys.
  const metadataJson = {
    name:        metadata.name,
    symbol:      metadata.symbol,
    description: metadata.description,
    image:       "https://via.placeholder.com/400x400/0A0F1E/3B82F6?text=🎟️",
    attributes:  metadata.attributes,
    properties: {
      files:    [{ uri: "", type: "image/png" }],
      category: "image",
    },
  };
  const uri = `data:application/json;base64,${btoa(JSON.stringify(metadataJson))}`;

  // Create the NFT on-chain via Metaplex UMI
  // sellerFeeBasisPoints = 250 (2.5% royalty enforced by our marketplace)
  const { signature } = await createNft(umi, {
    mint:                 mintKeypair,
    name:                 metadata.name,
    symbol:               metadata.symbol,
    uri,
    sellerFeeBasisPoints: percentAmount(2.5), // 2.5% royalty
    isMutable:            false,              // Ticket metadata is permanent
    // Creators: the seller is the sole creator for MVP
    creators: [
      {
        address: umi.identity.publicKey,
        verified: true,
        share: 100,
      },
    ],
  }).sendAndConfirm(umi);

  const mintAddress = mintKeypair.publicKey.toString();

  console.log(
    `[mintTicketNFT] Minted NFT ${mintAddress} in tx ${base58.deserialize(signature)[0]}`
  );

  return mintAddress;
}

// ── listTicketOnChain ─────────────────────────────────────────
// Calls the Anchor list_ticket instruction.
//
// This deposits the NFT from the seller's ATA into the escrow ATA
// owned by the listing PDA.  Price is stored on-chain.
//
// Returns the transaction signature.

export interface ListTicketParams {
  mintAddress: string;
  priceLamports: number;
  sellerPublicKey: string;
  royaltyRecipient: string;
  signTransaction: any;
}

export async function listTicketOnChain(params: ListTicketParams): Promise<string> {
  const {
    mintAddress,
    priceLamports,
    sellerPublicKey,
    royaltyRecipient,
    signTransaction,
  } = params;

  const connection = getConnection();
  const seller     = new PublicKey(sellerPublicKey);
  const mint       = new PublicKey(mintAddress);
  const royalty    = new PublicKey(royaltyRecipient);

  // Build a wallet for AnchorProvider
  const walletAdapter = {
    publicKey: seller,
    signTransaction,
    signAllTransactions: async (txs: Transaction[]) =>
      Promise.all(txs.map(signTransaction)),
  };

  const provider = new AnchorProvider(
    connection,
    walletAdapter as any,
    { commitment: "confirmed" }
  );
  const program = new Program(IDL as any, provider);

  // Derive PDA seeds: ["listing", mint, seller]
  const [listingPDA] = PublicKey.findProgramAddressSync(
    [Buffer.from("listing"), mint.toBuffer(), seller.toBuffer()],
    getProgramId()
  );

  // The escrow ATA is the associated token account owned by the listing PDA
  const { getAssociatedTokenAddressSync } = await import("@solana/spl-token");
  const sellerATA = getAssociatedTokenAddressSync(mint, seller);
  const escrowATA = getAssociatedTokenAddressSync(mint, listingPDA, true);

  const tx = await (program as any).methods
    .listTicket(new BN(priceLamports), royalty)
    .accounts({
      seller:              seller,
      mint:                mint,
      sellerTokenAccount:  sellerATA,
      listing:             listingPDA,
      escrowTokenAccount:  escrowATA,
      tokenProgram:        anchor.utils.token.TOKEN_PROGRAM_ID,
      associatedTokenProgram: anchor.utils.token.ASSOCIATED_PROGRAM_ID,
      systemProgram:       web3.SystemProgram.programId,
      rent:                web3.SYSVAR_RENT_PUBKEY,
    })
    .rpc({ commitment: "confirmed" });

  return tx;
}

// ── cancelListingOnChain ──────────────────────────────────────
// Calls the Anchor cancel_listing instruction.
// Returns the NFT from escrow to the seller.

export async function cancelListingOnChain(params: {
  mintAddress: string;
  sellerPublicKey: string;
  signTransaction: any;
}): Promise<string> {
  const { mintAddress, sellerPublicKey, signTransaction } = params;
  const connection = getConnection();
  const seller     = new PublicKey(sellerPublicKey);
  const mint       = new PublicKey(mintAddress);

  const walletAdapter = {
    publicKey: seller,
    signTransaction,
    signAllTransactions: async (txs: Transaction[]) =>
      Promise.all(txs.map(signTransaction)),
  };

  const provider = new AnchorProvider(connection, walletAdapter as any, {
    commitment: "confirmed",
  });
  const program = new Program(IDL as any, provider);

  const [listingPDA] = PublicKey.findProgramAddressSync(
    [Buffer.from("listing"), mint.toBuffer(), seller.toBuffer()],
    getProgramId()
  );

  const { getAssociatedTokenAddressSync } = await import("@solana/spl-token");
  const sellerATA = getAssociatedTokenAddressSync(mint, seller);
  const escrowATA = getAssociatedTokenAddressSync(mint, listingPDA, true);

  const tx = await (program as any).methods
    .cancelListing()
    .accounts({
      seller:              seller,
      mint:                mint,
      listing:             listingPDA,
      escrowTokenAccount:  escrowATA,
      sellerTokenAccount:  sellerATA,
      tokenProgram:        anchor.utils.token.TOKEN_PROGRAM_ID,
      associatedTokenProgram: anchor.utils.token.ASSOCIATED_PROGRAM_ID,
      systemProgram:       web3.SystemProgram.programId,
      rent:                web3.SYSVAR_RENT_PUBKEY,
    })
    .rpc({ commitment: "confirmed" });

  return tx;
}

// ── TicketNFT type ────────────────────────────────────────────
export interface TicketNFT {
  mintAddress: string;
  name: string;
  symbol: string;
  uri: string;
  attributes?: NFTAttribute[];
}

// ── fetchWalletNFTs ───────────────────────────────────────────
// Fetches all NFTs owned by a wallet that were minted by the
// Ticket Mint program (filtered by symbol = "TMKT").
//
// Uses Metaplex UMI fetchAllDigitalAssetByOwner — this queries
// the RPC for all token accounts + Metadata PDAs in one call.

export async function fetchWalletNFTs(walletAddress: string): Promise<TicketNFT[]> {
  // Build a minimal UMI instance (no signer needed for reads)
  const umi = createUmi(RPC_ENDPOINT).use(mplTokenMetadata());

  const owner = umiPublicKey(walletAddress);

  // Fetch all digital assets (NFTs) owned by this wallet
  // This uses the Metaplex DAS (Digital Asset Standard) RPC method
  // on supported RPC providers (Helius, etc.).  Falls back to
  // getTokenAccountsByOwner on standard devnet RPC.
  let assets: DigitalAsset[] = [];
  try {
    assets = await fetchAllDigitalAssetByOwner(umi, owner);
  } catch (err) {
    console.warn("[fetchWalletNFTs] fetchAllDigitalAssetByOwner failed:", err);
    // Fallback: return empty array — user can refresh
    return [];
  }

  // Filter to Ticket Mint NFTs only (symbol = "TMKT")
  const ticketNFTs: TicketNFT[] = [];

  for (const asset of assets) {
    const metadata = asset.metadata;
    if (metadata.symbol !== "TMKT") continue;

    // Try to parse attributes from the URI (data URI for MVP)
    let attributes: NFTAttribute[] | undefined;
    try {
      const uri = metadata.uri;
      if (uri.startsWith("data:application/json;base64,")) {
        const json = JSON.parse(atob(uri.split(",")[1]));
        attributes = json.attributes;
      } else if (uri.startsWith("http")) {
        const res = await fetch(uri);
        const json = await res.json();
        attributes = json.attributes;
      }
    } catch {
      // Metadata parse failure is non-fatal
    }

    ticketNFTs.push({
      mintAddress: asset.mint.publicKey.toString(),
      name:        metadata.name,
      symbol:      metadata.symbol,
      uri:         metadata.uri,
      attributes,
    });
  }

  return ticketNFTs;
}
